- hosts: webservers
  become: true
  tasks:
    - name: install apache2
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

    - name: ensure apache2 started
      service: name=apache2 state=started enabled=yes

    - name: esure mod-wsgi enabled
      apache2_module: state=present name=wsgi
      notify: restart apache2

    - name: copy demo app source
      apache_module: src=demo/app dest=/car/www/demo mode=0755
      notify: restart apache2
    
    - name: copy apache virtual host config
      copy: src=demo/demo.conf dest=/etc/apache2/sites-available mode=0755 

    handlers:
    - name: restart apache2
      service: name apache2 state=restarted
        


